logging:
  level:
    dk:
      fust:
        networksimulator: debug

spring:
  datasource:
    url: jdbc:postgresql://localhost:5532/network_simulator
    username: network_simulator_user
    password: network_simulator_password
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
server:
  port: 9898
