network-simulator:
  throttling:
    chunk-size: ${CHUNK_SIZE:100} # bytes

spring:
  application:
    name: Network Simulator
  profiles:
    active:
      - h2

springdoc:
  writer-with-order-by-keys: true
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui/index.html
    operations-sorter: alpha # Sort endpoints alphabetically
    tags-sorter: alpha # Sort tags (controllers) alphabetically

server:
  port: 9898
